image: igeolise/scalajs-test-runner

variables:
  SBT: sbt -sbt-dir "$CI_PROJECT_DIR/cache/.sbt" -ivy "$CI_PROJECT_DIR/cache/.ivy2"

before_script:
  - export COURSIER_CACHE="$CI_PROJECT_DIR/cache/.coursier-cache"

cache:
  paths:
  - cache/
  key: "$CI_BUILD_REF_NAME"

scalastyle:
  stage: build
  script:
    - $SBT scalastyle

scapegoat:
  stage: build
  script:
    - $SBT scapegoat

server_test:
  stage: test
  script:
    - $SBT server/test

fast_opt_test:
  stage: test
  script:
    - $SBT 'set scalaJSStage in Global := FastOptStage' 'client/test'

full_opt_test:
  stage: test
  script:
    - $SBT 'set scalaJSStage in Global := FullOptStage' 'client/test'

chromium_fast_opt_test:
  stage: test
  script:
    - Xvfb :1 &
    - DISPLAY=:1 $SBT 'set scalaJSStage in Global := FastOptStage' 'client/chromeDocker:test'

chromium_full_opt_test:
  stage: test
  script:
    - Xvfb :1 &
    - DISPLAY=:1 $SBT 'set scalaJSStage in Global := FullOptStage' 'client/chromeDocker:test'