image: openjdk:8

variables:
  SBT_VERSION: "0.13.13"
  SBT_PATH: "/opt/sbt-launcher-packaging-${SBT_VERSION}/bin"
  SBT: sbt -sbt-dir $CI_PROJECT_DIR/cache/.sbt -ivy $CI_PROJECT_DIR/cache/.ivy2

before_script:
  - curl -sL https://deb.nodesource.com/setup_7.x | bash
  - apt-get install -y nodejs
  - npm install jsdom
  - curl -SL https://dl.bintray.com/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | tar xz -C /opt/
  - export PATH=$PATH:$SBT_PATH

cache:
  paths:
  - cache/

scalastyle:
  stage: build
  script:
    - $SBT scalastyle

scapegoat:
  stage: build
  script:
    - $SBT scapegoat

server_test:
  stage: test
  script:
    - $SBT server/test

fast_opt_test:
  stage: test
  script:
    - $SBT 'set scalaJSStage in Global := FastOptStage' 'client/test'

full_opt_test:
  stage: test
  script:
    - $SBT 'set scalaJSStage in Global := FullOptStage' 'client/test'