image: openjdk:8

variables:
  SBT_VERSION: "0.13.13"
  SBT_PATH: "/opt/sbt-launcher-packaging-${SBT_VERSION}/bin"
  PHANTOMJS_VERSION: "2.1.1"
  PHANTOMJS_PATH: "/opt/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64/bin"

before_script:
  - curl -SL https://dl.bintray.com/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | tar xz -C /opt/
  - curl -SL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar xj -C /opt/
  - export PATH=$PATH:$SBT_PATH
  - export PATH=$PATH:$PHANTOMJS_PATH

scalastyle:
  stage: build
  script:
    - sbt scalastyle

scapegoat:
  stage: build
  script:
    - sbt scapegoat

server_test:
  stage: test
  script:
    - sbt server/test

fast_opt_test:
  stage: test
  script:
    - sbt 'set scalaJSStage in Global := FastOptStage' 'client/test'

full_opt_test:
  stage: test
  script:
    - sbt 'set scalaJSStage in Global := FullOptStage' 'client/test'