image: openjdk:8-alpine

variables:
  SBT_VERSION: "0.13.13"
  SBT_PATH: "/opt/sbt-launcher-packaging-${SBT_VERSION}/bin"

before_script:
  - apk --no-cache add bash curl
  - mkdir /opt
  - curl -SL https://dl.bintray.com/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | tar xz -C /opt/

scalastyle:
  stage: build
  script:
    - $SBT_PATH/sbt scalastyle