language: scala
scala:
  - "2.11.4"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "client/fullOptStage::test-only -- --throw"
  - sbt ++$TRAVIS_SCALA_VERSION "server/test-only -- --throw"
sudo: false
cache:
  directories:
  - $HOME/.ivy2