language: scala
scala:
  - "2.11.7"
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION scapegoat
  - sbt ++$TRAVIS_SCALA_VERSION 'clean' 'set scalaJSStage in Global := FastOptStage' "client/test"
  - sbt ++$TRAVIS_SCALA_VERSION 'clean' 'set scalaJSStage in Global := FullOptStage' "client/test"
  - sbt ++$TRAVIS_SCALA_VERSION "server/test"
sudo: false
cache:
  directories:
  - $HOME/.ivy2
addons:
  firefox: latest