language: scala
scala:
  - "2.11.2"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION client/fullOptStage::test
  - sbt ++$TRAVIS_SCALA_VERSION server/test